# Generated by Django 4.2.7 on 2023-12-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_players", models.IntegerField()),
                ("players", models.JSONField(default=list)),
                ("current_turn", models.IntegerField(default=0)),
                ("game_status", models.CharField(default="not_started", max_length=20)),
                ("treasury", models.IntegerField()),
                ("deck_card_counts", models.JSONField(default=dict)),
            ],
        ),
    ]
