# Generated by Django 4.2.7 on 2023-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_logic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="current_action",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="current_action_player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
